theme: jekyll-theme-tactile

defaults:
  - scope:
      path: "screenshots"
    values:
      image: true
      
title: Caddisfly Screenshots
description: View app screenshots

github:
  zip_url: http://example.com/download.zip
  another_url: another value
